### ISSUE TITLE
ERROR: lazy loading failed for package ‘stylo2gg’

### ISSUE THREAD

**Issue by doeparen** [jmclawson/stylo2gg#1]
Hi!

Thanks for what seems to be a great visual add-on to the stylo package! I Have tried to install it with both `devtools` and `remotes` but keep getting the same error message, even after updating my RStudio.

Best,
Josef

```
> devtools::install_github("jmclawson/stylo2gg")
Downloading GitHub repo jmclawson/stylo2gg@HEAD
✓  checking for file ‘/private/var/folders/bx/ncz7hxbj4k3cnbrcw93j1ndr0000gp/T/RtmpBRxeSp/remotes24963cfb24ae/jmclawson-stylo2gg-1a27f86/DESCRIPTION’ ...
─  preparing ‘stylo2gg’:
✓  checking DESCRIPTION meta-information ...
─  checking for LF line-endings in source and make files and shell scripts
─  checking for empty or unneeded directories
─  building ‘stylo2gg_0.7.3.tar.gz’
   
* installing *source* package ‘stylo2gg’ ...
** using staged installation
** R
** byte-compile and prepare package for lazy loading
Error in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]) : 
  there is no package called ‘lemon’
Calls: <Anonymous> ... loadNamespace -> withRestarts -> withOneRestart -> doWithOneRestart
Execution halted
ERROR: lazy loading failed for package ‘stylo2gg’
* removing ‘/Library/Frameworks/R.framework/Versions/4.0/Resources/library/stylo2gg’
Warning message:
In i.p(...) :
  installation of package ‘/var/folders/bx/ncz7hxbj4k3cnbrcw93j1ndr0000gp/T//RtmpBRxeSp/file2496c253ac9/stylo2gg_0.7.3.tar.gz’ had non-zero exit status

> remotes::install_github("jmclawson/stylo2gg")
Downloading GitHub repo jmclawson/stylo2gg@HEAD
✓  checking for file ‘/private/var/folders/bx/ncz7hxbj4k3cnbrcw93j1ndr0000gp/T/RtmpBRxeSp/remotes24966c7522ee/jmclawson-stylo2gg-1a27f86/DESCRIPTION’ ...
─  preparing ‘stylo2gg’:
✓  checking DESCRIPTION meta-information ...
─  checking for LF line-endings in source and make files and shell scripts
─  checking for empty or unneeded directories
─  building ‘stylo2gg_0.7.3.tar.gz’
   
* installing *source* package ‘stylo2gg’ ...
** using staged installation
** R
** byte-compile and prepare package for lazy loading
Error in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]) : 
  there is no package called ‘lemon’
Calls: <Anonymous> ... loadNamespace -> withRestarts -> withOneRestart -> doWithOneRestart
Execution halted
ERROR: lazy loading failed for package ‘stylo2gg’
* removing ‘/Library/Frameworks/R.framework/Versions/4.0/Resources/library/stylo2gg’
Warning message:
In i.p(...) :
  installation of package ‘/var/folders/bx/ncz7hxbj4k3cnbrcw93j1ndr0000gp/T//RtmpBRxeSp/file24967e486ee2/stylo2gg_0.7.3.tar.gz’ had non-zero exit status```

**Comment by jmclawson** [comment]
Thanks for checking it out and letting me know about the error, which I think is now fixed. 

Explanation: Since this was the first R package I attempted, it seems I made an error in the way I referenced a suggested package, "Lemon," which wouldn't have been installed by default. I've worked around this error by by moving the package into the list of required packages, so that it will get installed by default; I'm sure there's a better solution, but it would take a little more time to work out.

I hope the package proves useful to you! Please let me know if any other problems crop up.

**Comment by doeparen** [comment]
Cheers, I have now been able to install the package (with its dependencies) and tried it out. Great also with your provided explanation. I must say, the provided visualization settings looks awesome and the package is incredibly convenient to use for more advance stylometry tasks - so thanks a lot for developing it! I will see to spread the word of `stylo2gg` to all potential `stylo` users I know.

**Comment by jmclawson** [comment]
I’m very glad you’re finding it potentially useful! My idle coding often goes overboard when I’m trying out something new; it feels much more justified when others can use it, too. Since the installation problems might mean that you’re the first person to put it through the paces besides me, I’m especially eager to hear of any other problems or sticking points you run into.

**Comment by doeparen** [comment]
Hi again! I continue to enjoy your package! I am writing up my PhD dissertation where I use it but have one problem with the presentation (which is not really an issue with the package per se but maybe you can help me since you have written the function): how do I change color on the arrows and the words in the PCA (going to move from light gray to something more articulated and have tried all ggplot commands I know but nothing seems to work)? Thanks!
